### ISSUE TITLE
Deploying Dash apps on AWS

### ISSUE THREAD

**Issue by firasm** [ubco-mds-2020-labs/dashboard-project-group14#10]
Related to #8 again, the [Lecture instructions](https://firas.moosvi.com/courses/data551/class/4-maps-deployment.html) only include deployment of the dashboard on Heroku, but it's pretty similar (moderately more complicated) to deploy things on AWS. 

Here is a [guide that seems promising](https://korniichuk.medium.com/dash-on-aws-44a0f50a030a). 

That being said, you should make sure it's deployed on Heroku first because it's a lot simpler and you want to make sure you have a minimally viable product deployed on Heroku.

**Comment by WraySmith** [comment]
Thanks @firasm, the plan will definitely be to deploy on Heroku first and move to AWS only after (as an 'enhanced' deployment).  I've deployed to AWS before by building a [Shiny server on EC2](https://app.waterexplorer.net/shinyCFA/) and @mqharris has done the same sort of thing on DigitalOcean (and I think we've both deployed to Heroku at some point). I've run into problem with speed on the free tier of Heroku (mainly from large computations) so was thinking we might run into this with the potential network graph #9, although it would still be interesting to do even if this wasn't an issue.

At this point was thinking that if we're potentially going this route, consideration of the database format to use might be worth thinking about (NoSQL vs SQL).

**Comment by WraySmith** [comment]
Leaving this open but currently not in development.

**Comment by WraySmith** [comment]
Performance of the app on Heroku is good after vectorizing all operations, closing this issue.
