### ISSUE TITLE
Group Discussion Suggestions

### ISSUE THREAD

**Issue by WraySmith** [ubco-mds-2020-labs/dashboard-project-group14#55]
- Better description of what it does
- Link to source website / brief explanation of what mechanic/categories is
- Making tabs more obvious
- Change up bar chart type - make obvious that user can select year ranges
- Highlight user selection areas to be easily found

**Comment by RyKoe** [comment]
Firas comments:
- First tab has a lot of white space
- Maybe put first to graph side by side (I'm not sure how I feel about that)
- Dropdown can be changed to have sub categories which sorts them into how dense the data is.
- Bottom graphs first page could have their axis swapped
Others commets:
- Confused by the comparison graphs on the bottom

**Comment by mqharris** [comment]
- 2nd half of 1st wasn't immediately clear, i.e. it took a second to realize you were comparing the same things over different year range. The explanation exists to the left already, but maybe make the `compare the top 5 categories, mechanics and publishers between time periods.` bit bolder or a title
- explain user rating

**Comment by WraySmith** [comment]
Firas presentation feedback:

- Increase height of the middle pane so there are no drop downs
- I have mixed feelings about the datatable and whether it adds value or not ; definitely a cool feature though!
- Agree with some user instructions, perhaps some questions/sign posts to guide the user
- I’d suggest adding some headings/categories
- Milton Bradley vs FF games colours are too similar; maybe a faceted plot would be better here as so many points overlap? Or at the very least specify a different colour scheme
- I would strongly suggest flipping your X and Y axes so that the text is more easily readable on the Y-axis (!!)
- I’d suggest a violin plot showing the distribution of ratings for each game instead of an average score. I suppose this depends on what your Research question is

General comments from class:

- fonts for the labels are a bit small and hard to see
- Consider turning the bar chart sideways so the labels are easier to read (y axis) and so the x axis is the rating
- Table of values was a bit overwhelming and wasn't nicely formatted
- A lot of white space on the dashboard

**Comment by WraySmith** [comment]
Group comments merged into #34 and #35.
