### ISSUE TITLE
Look into Dash Cytoscape for network graphs

### ISSUE THREAD

**Issue by firasm** [ubco-mds-2020-labs/dashboard-project-group14#9]
In Issue #8, it was mentioned you wanted to create some Network Graphs. Those weren't really discussed in detail in 550 except to mention that they existed, mostly because they have limited utility.

For your application though, I can see a good use-case for Network Graphs. Network graphs don't exist by default in Altair, but there is another library, [`nx_altair` that builds network graphs with altair](https://github.com/Zsailer/nx_altair) but that's only if you're feeling brave.

A better way to do this would probably be to use the poorly library. Have a look at [this article](https://medium.com/plotly/exploring-and-investigating-network-relationships-with-plotlys-dash-and-dash-cytoscape-ec625ef63c59) that shows how to make network graphs in plotly and control it with Dash.

Here's an example:

![1*t3wDztpY8lTFrMBtko-4Cw](https://user-images.githubusercontent.com/2507459/109260543-29426300-77b3-11eb-8232-dc941a3607b8.gif)

**Comment by WraySmith** [comment]
Thanks @firasm the article has similar functionality to what I was thinking about, allowing a user to start reducing the amount of points by interactive filters (via dropdowns or sliders). I'll start with the plotly library. If a network graph doesn't end up making sense, may fall back to a clustering type of plot without connections (still allowing vis in 3D space).

**Comment by WraySmith** [comment]
I'm happy to start working on this side project as we go along.

**Comment by WraySmith** [comment]
Planning on going with a plotly 3D graph instead of plotly cytograph to allow 3D exploration of data
